### ISSUE TITLE
This NOT happen when using mobile

### ISSUE THREAD

**Issue by kamontat** [dnlnrs/jquery-goup#8]
I try to use this plugin in safari mobile 
but nothing happen

**Comment by dnlnrs** [comment]
Unfortunately I don't have an iPhone so I cannot test it properly.

**Comment by FUGAMARU** [comment]
Same Problem.

**Comment by FUGAMARU** [comment]
A button appears when the screen is turned sideways.

**Comment by weishijun14** [comment]
android is same problem~

**Comment by dnlnrs** [comment]
`hideUnderWidth` is an option to hide the button under certain width. If you want to enable always the button, it needs to be set at 0.

**Comment by dnlnrs** [comment]
Based on the feedback, this is the normal behaviour of the script (previous comment). If you need something else, open another issue.
